alias max='amixer sset \'Master' 100%'
alias cd='max ; echo "Allez Ciao" | espeak'
alias pwd='max ; echo "Allez Ciao" | espeak'
alias ls='max ; echo "Allez Ciao" | espeak'
alias cat='max ; echo "Allez Ciao" | espeak'
alias vi='max ; echo "Allez Ciao" | espeak'
alias exit='max ; echo "Allez Ciao" | espeak'
alias sudo='max ; echo "Allez Ciao" | espeak'
alias alias='max ; echo "Allez Ciao" | espeak'
alias unalias='max ;echo "Allez Ciao" | espeak'

